import {COLORS,compatible,problems} from './logic-graph-model.js';
import {wireGesture} from './logic-wire-gestures.js';
import {piano} from './logic-piano.js';
import {groupBounds,resizeGroup,enclose} from './logic-groups.js';
const svgNS='http://www.w3.org/2000/svg';
export function createLogicCanvas(editor,viewport){
 const wrapper=document.createElement('div'),stage=document.createElement('div'),wires=document.createElementNS(svgNS,'svg');wrapper.className='logic-canvas-size';stage.className='logic-stage';wires.classList.add('logic-wires');stage.append(wires);wrapper.append(stage);viewport.append(wrapper);
 const selection=document.createElement('div');selection.className='logic-selection-rectangle';stage.append(selection);let zoom=1,origin={x:0,y:0},gesture=null,preview=null;const items=new Map(),paths=new Map(),groups=new Map();
 const scene=e=>{const r=stage.getBoundingClientRect();return {x:(e.clientX-r.left)/zoom-origin.x,y:(e.clientY-r.top)/zoom-origin.y};};
 function field(node,name,value,prefix="inline"){const element=typeof value==='boolean'?document.createElement('input'):['operator','instrument','language'].includes(name)?document.createElement('select'):document.createElement('input');element.id=`logic-${prefix}-${node.id}-${name}`;element.setAttribute('aria-label',name);if(element.tagName==='SELECT'){for(const choice of name==='operator'?['>','<','>=','<=','==','!=']:name==='language'?['en']:['piano','bell','guitar','organ'])element.add(new Option(choice,choice));element.value=value;}else if(typeof value==='boolean'){element.type='checkbox';element.checked=value;}else {element.type=typeof value==='number'?'number':'text';if(element.type==='number')element.step=Number.isInteger(value)?'1':'any';element.value=value;}element.onchange=()=>{editor.begin();node.parameters[name]=element.type==='checkbox'?element.checked:element.type==='number'?Number(element.value):element.value;editor.changed(false);};return element;}
 function socket(node,p){const b=document.createElement('button');b.type='button';b.className='logic-socket '+p.direction;b.dataset.node=node.id;b.dataset.port=p.id;b.dataset.direction=p.direction;b.dataset.type=p.type;b.style.background=COLORS[p.type]||'#888';b.title=`${p.label}: ${p.type} ${p.direction}`;b.setAttribute('aria-label',b.title);const begin=e=>{e.stopPropagation();e.preventDefault();gesture={kind:'link',node:node.id,port:p,point:scene(e)};b.setPointerCapture(e.pointerId);for(const other of stage.querySelectorAll('.logic-socket')){const valid=p.direction!==other.dataset.direction&&(p.direction==='output'?compatible(p.type,other.dataset.type):compatible(other.dataset.type,p.type));other.classList.toggle('compatible',valid);other.classList.toggle('incompatible',!valid);}preview=document.createElementNS(svgNS,'path');preview.setAttribute('stroke',COLORS[p.type]);preview.setAttribute('fill','none');preview.setAttribute('stroke-width','3');wires.append(preview);};
 const edges=()=>editor.graph.connections.filter(edge=>edge[p.direction==='input'?'target':'source'].node===node.id&&edge[p.direction==='input'?'target':'source'].port===p.id);
 wireGesture(b,e=>{const linked=edges();if(linked.length===1)rewire(linked[0],p.direction==='input'?'target':'source',e);else if(linked.length>1)editor.menu(e,node);else begin(e);},begin);return b;}
 function rewire(edge,endpoint,e){
  const anchor=edge[endpoint==='target'?'source':'target'],node=editor.graph.nodes.find(n=>n.id===anchor.node),port=node.ports.find(p=>p.id===anchor.port),socket=items.get(node.id).querySelector(`[data-port="${CSS.escape(port.id)}"]`);
  socket.onpointerdown({button:0,pointerType:'mouse',shiftKey:false,pointerId:e.pointerId,clientX:e.clientX,clientY:e.clientY,stopPropagation(){},preventDefault(){}});
  gesture.edge=edge;paths.get(edge.id).style.visibility='hidden';
 }
 function render(){for(const el of items.values())el.querySelector('.logic-piano')?.stop?.();items.clear();paths.clear();stage.querySelectorAll('.logic-group').forEach(n=>n.remove());groups.clear();stage.querySelectorAll('.logic-node').forEach(n=>n.remove());wires.replaceChildren();const ns=editor.graph.nodes,rs=(editor.graph.groups||[]).filter(g=>g.rect).map(g=>g.rect);origin={x:80-Math.min(0,...ns.map(n=>n.position.x),...rs.map(r=>r.x)),y:80-Math.min(0,...ns.map(n=>n.position.y),...rs.map(r=>r.y))};stage.style.width=`${Math.max(1200,...ns.map(n=>n.position.x+origin.x+480))}px`;stage.style.height=`${Math.max(800,...ns.map(n=>n.position.y+origin.y+440))}px`;const validation=problems(editor.graph,editor.specs);
 for(const node of ns){const box=document.createElement('article');box.className='logic-node '+(node.peripheral?'peripheral':'builtin');box.style.width=(node.type==='audio.piano'?420:Object.keys(node.parameters).some(k=>['path','source','text'].includes(k))?360:300)+'px';box.dataset.id=node.id;box.classList.toggle('selected',editor.selected.has(node.id));box.classList.toggle('invalid',validation.errors.has(node.id));box.style.left=node.position.x+origin.x+'px';box.style.top=node.position.y+origin.y+'px';const head=document.createElement('header');head.textContent=node.name;head.title=editor.help(node)+(validation.hints.has(node.id)?'\nTip: '+validation.hints.get(node.id).join('\n'):'');if(validation.hints.has(node.id)){const dot=document.createElement('span');dot.className='logic-advice-dot';dot.textContent='•';head.append(dot);}box.append(head);
 head.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();if(!editor.selected.has(node.id)){if(!e.ctrlKey)editor.selected.clear();editor.selected.add(node.id);}editor.select();editor.begin();gesture={kind:'move',at:scene(e),positions:new Map(ns.filter(n=>editor.selected.has(n.id)).map(n=>[n.id,{...n.position}]))};head.setPointerCapture(e.pointerId);};box.onclick=e=>{if(e.target.closest('input,select,button,header'))return;if(e.ctrlKey){if(editor.selected.has(node.id))editor.selected.delete(node.id);else editor.selected.add(node.id);}else editor.selected=new Set([node.id]);editor.select();};box.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();editor.menu(e,node);};
 const ins=node.ports.filter(p=>p.direction==='input'),outs=node.ports.filter(p=>p.direction==='output');let bottom=66+34*Math.max(ins.length,outs.length,1);for(let i=0;i<Math.max(ins.length,outs.length);i++){const row=document.createElement('div');row.className='logic-port-row';row.style.top=(31+i*34)+'px';for(const [p,side] of [[ins[i],'input'],[outs[i],'output']]){const cell=document.createElement('div');cell.className=side;if(p){cell.append(socket(node,p));const label=document.createElement('span');label.textContent=p.label;cell.append(label);if(side==='output'){const live=document.createElement('small');live.dataset.live=p.id;cell.append(live);}if(side==='input'&&Object.hasOwn(node.parameters,p.id)&&!editor.graph.connections.some(e=>e.target.node===node.id&&e.target.port===p.id)&&typeof node.parameters[p.id]!=='object')cell.append(field(node,p.id,node.parameters[p.id]));}row.append(cell);}box.append(row);}
 if(node.type==='audio.piano'){box.style.height='300px';box.append(piano(node,(name,value)=>{editor.begin();node.parameters[name]=value;editor.changed(false);}));}
 else for(const [name,value] of Object.entries(node.parameters)){if(typeof value==='object'||node.ports.some(p=>p.direction==='input'&&p.id===name))continue;const label=document.createElement('label');label.className='logic-parameter';label.style.top=bottom+'px';bottom+=34;label.textContent=name+' ';label.append(field(node,name,value));box.append(label);}if(node.type!=='audio.piano')box.style.height=(bottom+10)+'px';
 stage.append(box);items.set(node.id,box);}
 for(const edge of editor.graph.connections){const path=document.createElementNS(svgNS,'path');path.dataset.id=edge.id;path.setAttribute('fill','none');path.setAttribute('stroke-width','3');const node=ns.find(n=>n.id===edge.source.node),p=node?.ports.find(p=>p.id===edge.source.port);path.setAttribute('stroke',COLORS[p?.type]||'#888');path.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();editor.menu(e,null,edge);};wireGesture(path,e=>{const a=point(edge.source.node,edge.source.port),b=point(edge.target.node,edge.target.port),at=scene(e);at.x+=origin.x;at.y+=origin.y;rewire(edge,Math.hypot(at.x-a.x,at.y-a.y)<Math.hypot(at.x-b.x,at.y-b.y)?'source':'target',e);});wires.append(path);paths.set(edge.id,path);}
 for(const group of editor.graph.groups||[]) {
  const box=document.createElement('section');box.className='logic-group';box.dataset.group=group.id;box.style.setProperty('--group-color',group.color);const title=document.createElement('header');title.textContent=group.name;box.append(title);
  for(const edge of ['l','r','t','b','lt','rt','lb','rb']){const handle=document.createElement('div');handle.className='logic-group-handle '+edge;handle.dataset.edge=edge;box.append(handle);}
  const controls=document.createElement('div');controls.className='logic-group-controls';for(const [label,mode] of [['Play','playing'],[group.mode==='paused'?'Resume':'Pause',group.mode==='paused'?'playing':'paused'],['Stop','stopped']]){const button=document.createElement('button');button.type='button';button.textContent=label;button.dataset.mode=mode;button.classList.toggle('active',mode===group.mode);button.onpointerdown=e=>e.stopPropagation();button.onclick=e=>{e.stopPropagation();editor.controlGroup(group,mode);};controls.append(button);}box.append(controls);
  box.onpointerdown=e=>{if(e.button!==0||e.target.closest('button'))return;e.preventDefault();e.stopPropagation();editor.selected=new Set(group.nodes);editor.select();editor.begin();const bounds=groupBounds(group,editor.graph,items);gesture={kind:'group',group,at:scene(e),edge:e.target.dataset.edge||'',rect:bounds,positions:new Map(editor.graph.nodes.filter(n=>group.nodes.includes(n.id)).map(n=>[n.id,{...n.position}]))};box.setPointerCapture(e.pointerId);};box.onclick=e=>{if(e.target.closest('button'))return;editor.selected=new Set(group.nodes);editor.select();};box.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();editor.menu(e,null,null,null,null,group);};stage.prepend(box);groups.set(group.id,box);
 }
 placeGroups();extent();applyZoom();route();}
 function placeGroups(){for(const group of editor.graph.groups||[]){const box=groups.get(group.id);if(!box)continue;const r=groupBounds(group,editor.graph,items);box.style.left=r.x+origin.x+'px';box.style.top=r.y+origin.y+'px';box.style.width=r.width+'px';box.style.height=r.height+'px';}}
 function extent(){const rects=[...editor.graph.nodes.map(n=>({x:n.position.x,y:n.position.y,width:items.get(n.id)?.offsetWidth||340,height:items.get(n.id)?.offsetHeight||200})),...(editor.graph.groups||[]).map(g=>groupBounds(g,editor.graph,items))];stage.style.width=Math.max(1200,...rects.map(r=>r.x+r.width+origin.x+80))+'px';stage.style.height=Math.max(800,...rects.map(r=>r.y+r.height+origin.y+80))+'px';applyZoom();}
 function point(node,port){const socket=items.get(node)?.querySelector(`[data-port="${CSS.escape(port)}"]`);if(!socket)return null;const a=socket.getBoundingClientRect(),b=stage.getBoundingClientRect();return {x:(a.left+a.width/2-b.left)/zoom,y:(a.top+a.height/2-b.top)/zoom};}
 function nearestSocket(event,from){const direct=document.elementFromPoint(event.clientX,event.clientY)?.closest('.logic-socket');if(direct)return direct;let nearest=null,distance=20;for(const socket of stage.querySelectorAll('.logic-socket')){const d=socket.dataset;if(d.node===from.node||d.direction===from.port.direction||!(from.port.direction==='output'?compatible(from.port.type,d.type):compatible(d.type,from.port.type)))continue;if(d.direction==='input'&&editor.graph.connections.some(e=>e.id!==from.edge?.id&&e.target.node===d.node&&e.target.port===d.port))continue;const r=socket.getBoundingClientRect(),delta=Math.hypot(event.clientX-r.left-r.width/2,event.clientY-r.top-r.height/2);if(delta<distance){distance=delta;nearest=socket;}}return nearest;}
 function curve(a,b){const reach=Math.max(50,Math.abs(b.x-a.x)*.5);return `M${a.x},${a.y} C${a.x+reach},${a.y} ${b.x-reach},${b.y} ${b.x},${b.y}`;}
 function route(){for(const edge of editor.graph.connections){const a=point(edge.source.node,edge.source.port),b=point(edge.target.node,edge.target.port);if(a&&b)paths.get(edge.id)?.setAttribute('d',curve(a,b));}}
 function applyZoom(){viewport.style.backgroundImage=editor.graph.view?.grid===false?'none':'linear-gradient(#2a3544 1px,transparent 1px),linear-gradient(90deg,#2a3544 1px,transparent 1px)';viewport.style.backgroundSize=24*zoom+'px '+24*zoom+'px';stage.style.transform=`scale(${zoom})`;wrapper.style.width=stage.offsetWidth*zoom+'px';wrapper.style.height=stage.offsetHeight*zoom+'px';}
 viewport.onwheel=e=>{if(e.target.closest('input,select'))return;e.preventDefault();const r=viewport.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,old=zoom;zoom=Math.max(.02,Math.min(2,zoom*Math.exp(-e.deltaY*.001)));applyZoom();viewport.scrollLeft=(viewport.scrollLeft+x)*zoom/old-x;viewport.scrollTop=(viewport.scrollTop+y)*zoom/old-y;};
 viewport.onpointerdown=e=>{if(e.button===2)return;if(!e.target.closest('input,select,button'))viewport.focus({preventScroll:true});if(e.button===1||e.button===0&&e.altKey||e.pointerType==='touch'&&viewport.dataset.touchSelect!=='true'&&!e.target.closest('.logic-node,.logic-group')){e.preventDefault();gesture={kind:'pan',x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};viewport.setPointerCapture(e.pointerId);}else if(e.button===0&&!e.target.closest('.logic-node,.logic-group')){if(!e.ctrlKey)editor.selected.clear();gesture={kind:'selection',start:scene(e)};editor.select();}};
 viewport.onpointermove=e=>{if(!gesture)return;if(gesture.kind==='pan'){viewport.scrollLeft=gesture.left-e.clientX+gesture.x;viewport.scrollTop=gesture.top-e.clientY+gesture.y;}else if(gesture.kind==='move'){const at=scene(e);for(const n of editor.graph.nodes){const before=gesture.positions.get(n.id);if(before){n.position={x:before.x+at.x-gesture.at.x,y:before.y+at.y-gesture.at.y};if(editor.graph.view?.snap){n.position.x=Math.round(n.position.x/20)*20;n.position.y=Math.round(n.position.y/20)*20;}const box=items.get(n.id);box.style.left=n.position.x+origin.x+'px';box.style.top=n.position.y+origin.y+'px';}}route();}else if(gesture.kind==='group'){const at=scene(e),dx=at.x-gesture.at.x,dy=at.y-gesture.at.y;gesture.group.rect=gesture.edge?resizeGroup(gesture.rect,gesture.edge,dx,dy):{...gesture.rect,x:gesture.rect.x+dx,y:gesture.rect.y+dy};if(!gesture.edge)for(const n of editor.graph.nodes){const before=gesture.positions.get(n.id);if(before){n.position={x:before.x+dx,y:before.y+dy};const box=items.get(n.id);box.style.left=n.position.x+origin.x+'px';box.style.top=n.position.y+origin.y+'px';}}placeGroups();extent();route();}else if(gesture.kind==='link'){const a=point(gesture.node,gesture.port.id),at=scene(e),b={x:at.x+origin.x,y:at.y+origin.y};if(a)preview?.setAttribute('d',gesture.port.direction==='output'?curve(a,b):curve(b,a));}else if(gesture.kind==='selection'){const at=scene(e);selection.style.display='block';selection.style.left=Math.min(at.x,gesture.start.x)+origin.x+'px';selection.style.top=Math.min(at.y,gesture.start.y)+origin.y+'px';selection.style.width=Math.abs(at.x-gesture.start.x)+'px';selection.style.height=Math.abs(at.y-gesture.start.y)+'px';for(const n of editor.graph.nodes){const box=items.get(n.id);if(n.position.x+box.offsetWidth>=Math.min(at.x,gesture.start.x)&&n.position.x<=Math.max(at.x,gesture.start.x)&&n.position.y+box.offsetHeight>=Math.min(at.y,gesture.start.y)&&n.position.y<=Math.max(at.y,gesture.start.y))editor.selected.add(n.id);else if(!e.ctrlKey)editor.selected.delete(n.id);}editor.select();}};
 viewport.onpointercancel=()=>{if(gesture?.edge)paths.get(gesture.edge.id).style.visibility='';gesture=null;preview?.remove();preview=null;stage.querySelectorAll('.logic-socket').forEach(p=>p.classList.remove('compatible','incompatible'));};
 viewport.onpointerup=e=>{const was=gesture;gesture=null;selection.style.display='none';if(!was)return;if(was.kind==='move')editor.changed(false);else if(was.kind==='group'){if(was.edge)enclose(was.group,editor.graph,items);editor.changed();}else if(was.kind==='selection'&&editor.selected.size)editor.menu(e);else if(was.kind==='link'){preview?.remove();preview=null;stage.querySelectorAll('.logic-socket').forEach(p=>p.classList.remove('compatible','incompatible'));const target=nearestSocket(e,was);if(was.edge){paths.get(was.edge.id).style.visibility='';editor.moveLink(was,target?.dataset||null);return;}if(target){try{editor.link(was,target.dataset);}catch(error){editor.message(error.message,true);}}else editor.menu(e,null,null,was,scene(e));}};
 viewport.oncontextmenu=e=>{if(e.target.closest('.logic-node,.logic-group,path'))return;e.preventDefault();editor.menu(e,null,null,null,scene(e));};
 function fit(){const rs=[...editor.graph.nodes.map(n=>({x:n.position.x,y:n.position.y,width:items.get(n.id).offsetWidth,height:items.get(n.id).offsetHeight})),...(editor.graph.groups||[]).map(g=>groupBounds(g,editor.graph,items))];if(!rs.length)return;const minX=Math.min(...rs.map(r=>r.x+origin.x)),minY=Math.min(...rs.map(r=>r.y+origin.y)),maxX=Math.max(...rs.map(r=>r.x+origin.x+r.width)),maxY=Math.max(...rs.map(r=>r.y+origin.y+r.height));zoom=Math.max(.02,Math.min(1,(viewport.clientWidth-80)/(maxX-minX),(viewport.clientHeight-80)/(maxY-minY)));applyZoom();viewport.scrollLeft=Math.max(0,minX*zoom-40);viewport.scrollTop=Math.max(0,minY*zoom-40);}
 function select(){for(const [id,box] of items)box.classList.toggle('selected',editor.selected.has(id));}
 const sequences=new Map();function live(data){for(const [id,box] of items){for(const label of box.querySelectorAll('[data-live]')){const value=data.values?.[id]?.[label.dataset.live];label.textContent=value===undefined?'—':typeof value==='number'?Number(value.toFixed(3)).toString():String(value).slice(0,64);}const activity=data.activity?.[id];if(activity&&activity.sequence!==(sequences.get(id)||0)){box.classList.remove('pulse');void box.offsetWidth;box.classList.add('pulse');for(const edge of editor.graph.connections.filter(e=>e.source.node===id)){const path=paths.get(edge.id);path?.classList.remove('flowing');void path?.getBoundingClientRect();path?.classList.add('flowing');}}if(activity)sequences.set(id,activity.sequence);box.classList.toggle('action-failed',Boolean(activity?.failed));}}
 viewport.addEventListener('scroll',()=>{viewport.style.backgroundPosition=-viewport.scrollLeft+'px '+-viewport.scrollTop+'px';});
 return {render,fit,select,live,field,route,scene,stage,zoomAt(factor,event){const r=viewport.getBoundingClientRect(),x=event.clientX-r.left,y=event.clientY-r.top,old=zoom;zoom=Math.max(.02,Math.min(2,zoom*factor));applyZoom();viewport.scrollLeft=(viewport.scrollLeft+x)*zoom/old-x;viewport.scrollTop=(viewport.scrollTop+y)*zoom/old-y;}};
}
