let audio;
export function piano(node,change){
 const root=document.createElement('div');root.className='logic-piano';const row=document.createElement('div');row.className='logic-piano-tools';root.append(row);
 const instrument=document.createElement('select');instrument.id=`piano-instrument-${node.id}`;for(const name of ['piano','bell','guitar','organ'])instrument.add(new Option(name,name));instrument.value=node.parameters.instrument||'piano';instrument.onchange=()=>change('instrument',instrument.value);row.append(instrument);
 const octave=document.createElement('select');octave.id=`piano-octave-${node.id}`;for(let n=1;n<=7;n++)octave.add(new Option(`Octave ${n}`,n));octave.value=node.parameters.octave||4;octave.onchange=()=>change('octave',Number(octave.value));row.append(octave);
 const record=document.createElement('button'),play=document.createElement('button');record.type=play.type='button';record.textContent='Record';play.textContent='Play';row.append(record,play);
 const keys=document.createElement('div');keys.className='logic-piano-keys';root.append(keys);const held=new Map(),voices=new Map();let recording=false,started=0,notes=[],timers=[],recordTimer=null;
 function voice(pitch,on){if(on){if(voices.has(pitch))voice(pitch,false);audio||=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.type={piano:'triangle',bell:'sine',guitar:'triangle',organ:'sine'}[instrument.value];oscillator.frequency.value=440*2**((pitch-69)/12);gain.gain.value=.06;oscillator.connect(gain).connect(audio.destination);oscillator.start();voices.set(pitch,{oscillator,gain});}else {const v=voices.get(pitch);if(v){v.gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.08);v.oscillator.stop(audio.currentTime+.1);voices.delete(pitch);}}}
 function press(n,on){const pitch=12*(Number(octave.value)+1)+n;if(on){if(held.has(n))return;held.set(n,performance.now());voice(pitch,true);}else {const time=held.get(n);if(time===undefined)return;held.delete(n);voice(pitch,false);if(recording&&notes.length<128){notes.push({note:pitch,start:Math.max(0,(time-started)/1000),duration:Math.max(.01,(performance.now()-time)/1000),velocity:.75});}}keys.querySelector(`[data-note="${n}"]`)?.classList.toggle('pressed',on);}
 const letters=['A','W','S','E','D','F','T','G','Y','H','U','J','K'],names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B','C'];let white=0;
 for(let n=0;n<=12;n++){const key=document.createElement('button');key.type='button';key.dataset.note=n;const black=names[n].includes('#');key.className='logic-key '+(black?'black':'white');key.style.left=`${(black?white-.32:white)*12.5}%`;if(!black)white++;key.textContent=names[n]+' '+letters[n];key.onpointerdown=e=>{e.preventDefault();key.setPointerCapture(e.pointerId);press(n,true);};key.onpointerup=key.onpointercancel=()=>press(n,false);keys.append(key);}
 record.onclick=()=>{clearTimeout(recordTimer);if(recording){for(const n of [...held.keys()])press(n,false);recording=false;record.textContent='Record';change('notes',notes);}else {timers.forEach(clearTimeout);notes=[];started=performance.now();recording=true;record.textContent='Finish';change('notes',[]);recordTimer=setTimeout(()=>record.click(),59950);}};
 play.onclick=()=>{timers.forEach(clearTimeout);for(const n of node.parameters.notes||[]){timers.push(setTimeout(()=>voice(n.note,true),n.start*1000),setTimeout(()=>voice(n.note,false),(n.start+n.duration)*1000));}};
 root.tabIndex=0;root.onkeydown=e=>{if(e.target.matches('input,select'))return;const n=letters.indexOf(e.key.toUpperCase());if(n>=0&&!e.repeat){e.preventDefault();press(n,true);}};root.onkeyup=e=>{const n=letters.indexOf(e.key.toUpperCase());if(n>=0){e.preventDefault();press(n,false);}};
 root.stop=()=>{clearTimeout(recordTimer);for(const n of [...held.keys()])press(n,false);timers.forEach(clearTimeout);for(const pitch of [...voices.keys()])voice(pitch,false);};return root;
}
