let audio;
export function piano(node,change,prefix="piano"){
 const root=document.createElement('div');root.className='logic-piano';const row=document.createElement('div');row.className='logic-piano-tools';root.append(row);
 const instrument=document.createElement('select');instrument.id=`${prefix}-instrument-${node.id}`;for(const name of ['piano','bell','guitar','organ'])instrument.add(new Option(name,name));instrument.value=node.parameters.instrument||'piano';instrument.onchange=()=>change('instrument',instrument.value);row.append(instrument);
 const octave=document.createElement('select');octave.id=`${prefix}-octave-${node.id}`;for(let n=1;n<=7;n++)octave.add(new Option(`Octave ${n}`,n));octave.value=node.parameters.octave||4;octave.onchange=()=>change('octave',Number(octave.value));row.append(octave);
 const record=document.createElement('button'),play=document.createElement('button');record.type=play.type='button';record.className='logic-piano-icon logic-piano-record';play.className='logic-piano-icon logic-piano-play';row.append(record,play);
 const keys=document.createElement('div');keys.className='logic-piano-keys';root.append(keys);const held=new Map(),voices=new Map();let recording=false,started=0,notes=[],timers=[],recordTimer=null,playState='stopped',elapsed=0,playStarted=0;
 function icons(){record.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/></svg>';record.setAttribute('aria-pressed',String(recording));record.setAttribute('aria-label',recording?'Finish recording':'Record');record.title=recording?'Finish recording':'Record';play.innerHTML=playState==='playing'?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3h5v18H5zM14 3h5v18h-5z"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 2v20l17-10z"/></svg>';play.setAttribute('aria-label',playState==='playing'?'Pause':playState==='paused'?'Resume':'Play');play.title=play.getAttribute('aria-label');play.dataset.state=playState;}
 function silence(){timers.forEach(clearTimeout);timers=[];for(const pitch of [...voices.keys()])voice(pitch,false);}
 function stopPreview(){silence();playState='stopped';elapsed=0;icons();}
 icons();
 function voice(pitch,on){if(on){if(voices.has(pitch))voice(pitch,false);audio||=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.type={piano:'triangle',bell:'sine',guitar:'triangle',organ:'sine'}[instrument.value];oscillator.frequency.value=440*2**((pitch-69)/12);gain.gain.value=.06;oscillator.connect(gain).connect(audio.destination);oscillator.start();voices.set(pitch,{oscillator,gain});}else {const v=voices.get(pitch);if(v){v.gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.08);v.oscillator.stop(audio.currentTime+.1);voices.delete(pitch);}}}
 function press(n,on){const pitch=12*(Number(octave.value)+1)+n;if(on){if(held.has(n))return;held.set(n,performance.now());voice(pitch,true);}else {const time=held.get(n);if(time===undefined)return;held.delete(n);voice(pitch,false);if(recording&&notes.length<128){notes.push({note:pitch,start:Math.max(0,(time-started)/1000),duration:Math.max(.01,(performance.now()-time)/1000),velocity:.75});}}keys.querySelector(`[data-note="${n}"]`)?.classList.toggle('pressed',on);}
 const letters=['A','W','S','E','D','F','T','G','Y','H','U','J','K'],names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B','C'];let white=0;
 for(let n=0;n<=12;n++){const key=document.createElement('button');key.type='button';key.dataset.note=n;const black=names[n].includes('#');key.className='logic-key '+(black?'black':'white');key.style.left=`${(black?white-.32:white)*12.5}%`;if(!black)white++;key.textContent=names[n]+' '+letters[n];key.onpointerdown=e=>{e.preventDefault();key.setPointerCapture(e.pointerId);press(n,true);};key.onpointerup=key.onpointercancel=()=>press(n,false);keys.append(key);}
 record.onclick=()=>{clearTimeout(recordTimer);if(recording){for(const n of [...held.keys()])press(n,false);recording=false;change('notes',notes);}else {stopPreview();notes=[];started=performance.now();recording=true;change('notes',[]);recordTimer=setTimeout(()=>record.click(),59950);}icons();};
 play.onclick=()=>{if(recording)record.click();if(playState==='playing'){elapsed+=(performance.now()-playStarted)/1000;silence();playState='paused';icons();return;}silence();const melody=node.parameters.notes||[],end=Math.max(0,...melody.map(n=>n.start+n.duration));if(end<=elapsed){stopPreview();return;}playStarted=performance.now();playState='playing';icons();for(const n of melody){if(n.start+n.duration<=elapsed)continue;timers.push(setTimeout(()=>voice(n.note,true),Math.max(0,n.start-elapsed)*1000),setTimeout(()=>voice(n.note,false),(n.start+n.duration-elapsed)*1000));}timers.push(setTimeout(stopPreview,(end-elapsed)*1000+120));};
 root.tabIndex=0;root.onkeydown=e=>{if(e.target.matches('input,select'))return;const n=letters.indexOf(e.key.toUpperCase());if(n>=0&&!e.repeat){e.preventDefault();press(n,true);}};root.onkeyup=e=>{const n=letters.indexOf(e.key.toUpperCase());if(n>=0){e.preventDefault();press(n,false);}};
 root.finishRecording=()=>{if(recording)record.click();};root.stop=()=>{clearTimeout(recordTimer);for(const n of [...held.keys()])press(n,false);recording=false;stopPreview();};return root;
}
