import {LOGIC_CATALOG} from './logic-catalog.js';
import {LOGIC_HELP,PERIPHERAL_HELP} from './logic-help.js';
import {clone,createNode,connect,removeNodes,duplicate,compatible,specKey,problems,upgradeNodes} from './logic-graph-model.js';
import {groupSelection} from './logic-groups.js';
import {createLogicCanvas} from './logic-canvas.js';
import {helpIdForNode,openOnlineHelp} from './online-help.js';
const tr=value=>window.ElmaI18n?.t?.(value)||window.ElmaFirmwareI18n?.t?.(value)||value;
let buzzerPreviewContext=null;
function previewBuzzerLocally(node,graph,action){
 if(buzzerPreviewContext){buzzerPreviewContext.close().catch(()=>{});buzzerPreviewContext=null;}
 if(action==='stop')return;
 const Context=window.AudioContext||window.webkitAudioContext;if(!Context)throw Error('Audio preview is unavailable in this application.');
 const presets={beep:[[69,0,.25]],'double-beep':[[69,0,.18],[69,.30,.18]],alert:[[76,0,.16],[69,.22,.16],[76,.44,.24]],doorbell:[[76,0,.35],[72,.42,.55]],success:[[60,0,.16],[64,.20,.16],[67,.40,.30]]};
 const edge=graph.connections.find(item=>item.target.node===node.id&&item.target.port==='source'),source=edge&&graph.nodes.find(item=>item.id===edge.source.node),notes=source?.type==='audio.piano'&&Array.isArray(source.parameters?.notes)?source.parameters.notes.map(item=>[item.note,item.start,item.duration]):(presets[node.parameters.preset]||presets.beep);
 const context=new Context(),gain=context.createGain();gain.gain.value=.08;gain.connect(context.destination);buzzerPreviewContext=context;let end=.3;
 for(const [note,start,duration] of notes){const oscillator=context.createOscillator();oscillator.type='square';oscillator.frequency.value=node.parameters.buzzerMode==='active'?1800:440*Math.pow(2,(Number(note)-69)/12);oscillator.connect(gain);oscillator.start(context.currentTime+Number(start));oscillator.stop(context.currentTime+Number(start)+Number(duration));end=Math.max(end,Number(start)+Number(duration));}
 setTimeout(()=>{if(buzzerPreviewContext===context){context.close().catch(()=>{});buzzerPreviewContext=null;}},(end+.2)*1000);
}
export function createLogicsTab(options={}){
 const panel=document.getElementById('tab-logics');if(!panel)return null;
 let loaded=false,loading=false,busy=false,dirty=false,mode='playing',before=null,undo=[],redo=[],clipboard=null,menu=null;let remoteGroups=new Set();
 const status=panel.querySelector('[data-logic-status]'),saveButton=panel.querySelector('[data-logic-save]'),palette=panel.querySelector('[data-logic-palette]'),properties=panel.querySelector('[data-logic-properties]'),search=panel.querySelector('[data-logic-search]'),viewport=panel.querySelector('[data-logic-canvas]');
 const editor={graph:{schemaVersion:1,nodes:[],connections:[],groups:[],devices:[],view:{grid:true,snap:false}},specs:Object.values(LOGIC_CATALOG),selected:new Set(),
 message(text,error=false){status.textContent=tr(text);status.classList.toggle('error',error);},
 begin(){before=clone(editor.graph);},
 changed(render=true){if(before&&JSON.stringify(before)!==JSON.stringify(editor.graph)){undo.push(before);if(undo.length>100)undo.shift();redo=[];dirty=true;}before=null;options.onChange?.(clone(editor.graph));if(render)canvas.render();if(!render&&document.activeElement?.closest("[data-logic-properties]"))canvas.select();else editor.select();buttons();},
 select(){canvas.select();properties.replaceChildren();const node=editor.graph.nodes.find(n=>editor.selected.has(n.id));if(!node)return;const title=document.createElement('input');title.id='logic-selected-name';title.value=node.name;title.setAttribute('aria-label','Node name');title.onchange=()=>{editor.begin();node.name=title.value;editor.changed();};properties.append(title);const help=document.createElement('p');help.textContent=editor.help(node);properties.append(help);for(const [key,value] of Object.entries(node.parameters)){if(typeof value==='object'||key==='preset'&&editor.graph.connections.some(e=>e.target.node===node.id&&e.target.port==='source'))continue;const row=document.createElement('label');row.textContent=key+' ';row.append(canvas.field(node,key,value,"properties"));properties.append(row);}const found=problems(editor.graph,editor.specs);if(found.errors.has(node.id)){const p=document.createElement('p');p.className='error';p.textContent=found.errors.get(node.id).join(' ');properties.append(p);}},
 help(node){const definition=editor.specs.find(s=>specKey(s)===specKey(node)),help=LOGIC_HELP[node.type]||(node.type.startsWith('condition.')&&node.type!=='condition.if'&&node.type!=='condition.between'?['Compares A and B using the selected operator. Result is a Boolean, not an execution pulse.','Compare.Result → Rising Edge.Value → Repeat.In; Repeat.Out → Play.In.']:node.type.startsWith('value.')?['Outputs the value entered in this node. Connected inputs replace inline defaults.','Number.Value → Compare.B, or Text.Value → TTS.Text.']:null)||PERIPHERAL_HELP[node.type.split('.').at(-1)];return (definition?.description||help?.[0]||(node.type.startsWith('mainboard.')?(definition?.binding?.kind==='status'?'Reads the ESP’s live '+node.name+' parameter.':definition?.binding?.kind==='event'?'Emits a pulse when '+node.name+' occurs.':'Runs '+node.name+' when its execution input is triggered.'):definition?.title)||node.name)+'\nAccepts: '+node.ports.filter(p=>p.direction==='input').map(p=>`${p.label} (${p.type})`).join(', ')+'\nOutputs: '+node.ports.filter(p=>p.direction==='output').map(p=>`${p.label} (${p.type})`).join(', ')+'\nExample: '+(help?.[1]||(node.ports.some(p=>p.direction==='output'&&p.type==='boolean')?'Connect the Boolean value to Rising Edge, then connect Out to an action.':node.ports.some(p=>p.direction==='output'&&['number','analog','integer'].includes(p.type))?'Connect the value to Compare, then Rising Edge to an action.':'Connect an event execution output to the action input.'));},
 link(from,to){editor.begin();if(from.port.direction==='output')connect(editor.graph,from.node,from.port.id,to.node,to.port);else connect(editor.graph,to.node,to.port,from.node,from.port.id);editor.changed();},
 moveLink(from,to){editor.begin();const original=before;try{editor.graph.connections=editor.graph.connections.filter(e=>e.id!==from.edge.id);if(to){if(from.port.direction==='output')connect(editor.graph,from.node,from.port.id,to.node,to.port);else connect(editor.graph,to.node,to.port,from.node,from.port.id);}editor.changed();}catch(error){editor.graph=original;before=null;canvas.render();editor.message(error.message+'; original wire retained',true);}},
 controlGroup:async(group,state)=>{try {if(state==='playing'&&dirty)await save();if(!remoteGroups.has(group.id)){editor.begin();group.mode=state;editor.changed(false);await save();}else {let payload={group:{id:group.id,mode:state}},result;try{result=await request(payload);}catch(error){if(state==='playing'&&error.message.startsWith('RECOVERY_CONFIRMATION_REQUIRED:')&&confirm(error.message.replace('RECOVERY_CONFIRMATION_REQUIRED:','').trim()))result=await request({...payload,confirmUnsafeRestart:true});else throw error;}syncGroups(result.groups);if(result.warning){editor.message(result.warning,true);return;}}editor.message(`${group.name}: ${state}.${dirty?' Canvas edits still need Save & apply.':''}`);}catch(error){editor.message(error.message.replace('RECOVERY_CONFIRMATION_REQUIRED:','').trim(),true);}},
 testNode:async(node,action)=>{try{if(options.local){previewBuzzerLocally(node,editor.graph,action);editor.message(action==='play'?'Buzzer preview is playing through this phone or computer.':'Buzzer preview stopped.');return;}if(dirty)await save();const result=await request({test:{nodeId:node.id,action}});canvas.live(result.live||{});editor.message(action==='play'?'Buzzer test queued on the device.':'Buzzer stopped.');}catch(error){editor.message(error.message,true);}},
 menu(event,node=null,edge=null,origin=null,position=null,group=null){menu?.remove();menu=document.createElement('div');menu.className='logic-context-menu';menu.style.left=Math.min(event.clientX,window.innerWidth-330)+'px';menu.style.top=Math.min(event.clientY,window.innerHeight-400)+'px';document.body.append(menu);const action=(label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{menu.remove();try{Promise.resolve(fn()).catch(error=>editor.message(error.message,true));}catch(error){editor.message(error.message,true);}};menu.append(b);};
 action(options.local?'Save project':'Save & apply',save);action('Fit all',()=>canvas.fit());action('Undo',undoEdit);action('Redo',redoEdit);action('Copy selection',copy);if(clipboard)action('Paste',paste);for(const key of ['grid','snap'])action(`${key}: ${editor.graph.view[key]?'On':'Off'}`,()=>{editor.begin();editor.graph.view[key]=!editor.graph.view[key];editor.changed();});for(const state of ['playing','paused','stopped'])action('All automations: '+state,async()=>{if(state==='playing'&&dirty)await save();let payload={mode:state},result;try{result=await request(payload);}catch(error){if(state==='playing'&&error.message.startsWith('RECOVERY_CONFIRMATION_REQUIRED:')&&confirm(error.message.replace('RECOVERY_CONFIRMATION_REQUIRED:','').trim()))result=await request({...payload,confirmUnsafeRestart:true});else throw error;}mode=result.mode;editor.message(result.warning||'All automations: '+mode,!!result.warning);});
 if(group){action('Help / Documentation',()=>openOnlineHelp('logics.overview'));for(const state of ['playing','paused','stopped'])action('Automation: '+state,()=>editor.controlGroup(group,state));action('Ungroup',()=>{editor.begin();editor.graph.groups=editor.graph.groups.filter(g=>g.id!==group.id);editor.changed();});action('Delete group and contents',()=>{editor.begin();removeNodes(editor.graph,new Set(group.nodes));editor.graph.groups=editor.graph.groups.filter(g=>g.id!==group.id);editor.selected.clear();editor.changed();});action('Rename',()=>{const name=prompt('Automation name',group.name);if(name!==null){editor.begin();group.name=name;editor.changed();}});return;}
 if(node){if(!editor.selected.has(node.id))editor.selected=new Set([node.id]);editor.select();action('Help / Documentation',()=>openOnlineHelp(helpIdForNode(node)));for(const wire of editor.graph.connections.filter(e=>e.source.node===node.id||e.target.node===node.id)){const a=editor.graph.nodes.find(n=>n.id===wire.source.node),b=editor.graph.nodes.find(n=>n.id===wire.target.node);action(`Disconnect: ${a.name}.${wire.source.port} → ${b.name}.${wire.target.port}`,()=>{editor.begin();editor.graph.connections=editor.graph.connections.filter(e=>e.id!==wire.id);editor.changed();});}action('Properties',()=>{editor.select();panel.querySelector('.logic-inspector').open=true;});action('Local tip',()=>{editor.select();panel.querySelector('.logic-inspector').open=true;properties.scrollIntoView({block:'nearest'});});action('Duplicate',copySelection);action('Break all links',()=>{editor.begin();editor.graph.connections=editor.graph.connections.filter(e=>!editor.selected.has(e.source.node)&&!editor.selected.has(e.target.node));editor.changed();});action('Delete',deleteSelection);}
 else if(edge)action('Delete connection',()=>{editor.begin();editor.graph.connections=editor.graph.connections.filter(e=>e.id!==edge.id);editor.changed();});
 if(editor.selected.size&&!origin&&!edge){action('Group',()=>{editor.begin();groupSelection(editor.graph,editor.selected);editor.changed();});action('Drag selection',()=>editor.message('Grab a selected node header, or the group rectangle, to move it.'));}
 if(!edge){const input=document.createElement('input');input.id='logic-add-node-search';input.placeholder='Add node: search…';menu.append(input);const list=document.createElement('div');list.className='logic-menu-results';menu.append(list);const draw=()=>{list.replaceChildren();const specs=editor.specs.filter(s=>(!origin||s.ports.some(p=>p.direction!==origin.port.direction&&(origin.port.direction==='output'?compatible(origin.port.type,p.type):compatible(p.type,origin.port.type))))&&`${s.title} ${s.category} ${s.subcategory||''}`.toLowerCase().includes(input.value.toLowerCase()));for(const s of specs){const b=document.createElement('button');b.type='button';b.textContent=`${s.category} / ${s.title}`;b.onclick=()=>{menu.remove();add(s,position||canvas.scene(event),origin);};list.append(b);}};input.oninput=draw;draw();input.focus();}
 }
 };
 const canvas=createLogicCanvas(editor,viewport);
 function copy(){clipboard=clone({...editor.graph,nodes:editor.graph.nodes.filter(n=>editor.selected.has(n.id)),connections:editor.graph.connections.filter(e=>editor.selected.has(e.source.node)&&editor.selected.has(e.target.node))});}
 function paste(){if(!clipboard)return;editor.begin();const part=clone(clipboard);part.groups=(part.groups||[]).filter(g=>g.nodes.every(n=>part.nodes.some(node=>node.id===n)));const previous=new Set(part.groups.map(g=>g.id)),ids=duplicate(part,new Set(part.nodes.map(n=>n.id)));editor.graph.groups.push(...part.groups.filter(g=>!previous.has(g.id)));editor.graph.nodes.push(...part.nodes.filter(n=>ids.has(n.id)));editor.graph.connections.push(...part.connections.filter(e=>ids.has(e.source.node)));editor.selected=ids;editor.changed();}

 async function request(payload,live=false){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);let response;try{response=await fetch('/api/logics'+(live?'?live=1':''),{cache:'no-store',signal:controller.signal,...(payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{})});}finally{clearTimeout(timeout);}const result=await response.json();if(!response.ok||result.error)throw Error(result.error||`Logics request failed (${response.status})`);return result;}
 function buttons(){panel.querySelector('[data-logic-dirty]').textContent=busy?'Saving…':dirty?(options.local?'Project draft saved':'Unsaved changes — device runs last applied graph'):loaded?(options.local?'Saved in project':'Saved on device'):'';if(saveButton){saveButton.disabled=busy||!loaded;saveButton.textContent=busy?'Saving…':options.local?'Save project':'Save & apply';}}
 function syncGroups(groups){if(!groups)return;remoteGroups=new Set(groups.map(g=>g.id));for(const group of editor.graph.groups||[]){const remote=groups.find(g=>g.id===group.id);if(remote)group.mode=remote.mode;}for(const group of editor.graph.groups||[]){const box=canvas.stage.querySelectorAll('.logic-group');for(const element of box){if(element.dataset.group!==group.id)continue;const bs=element.querySelectorAll('button');bs[0].classList.toggle('active',group.mode==='playing');bs[1].textContent=tr(group.mode==='paused'?'Resume':'Pause');bs[1].classList.toggle('active',group.mode==='paused');bs[1].onclick=()=>editor.controlGroup(group,group.mode==='paused'?'playing':'paused');bs[2].classList.toggle('active',group.mode==='stopped');}}canvas.runtime(mode,groups);}
 async function load(){if(loading||loaded)return;loading=true;editor.message('Loading device Logics…');try{const result=await request();editor.graph=clone(result.graph);editor.graph.groups||=[];editor.graph.view||={grid:true,snap:false};editor.graph.devices||=[];editor.specs=[...Object.values(LOGIC_CATALOG).filter(s=>result.audioEnabled!==false||!s.type.startsWith('audio.')||s.type==='audio.piano'),...editor.graph.devices];for(const n of editor.graph.nodes){const s=editor.specs.find(s=>specKey(s)===specKey(n));n.ports||=clone(s?.ports||[]);n.parameters={...clone(s?.parameters||{}),...(n.parameters||{})};n.name||=s?.title||n.type;n.position||={x:0,y:0};}upgradeNodes(editor.graph,editor.specs);mode=result.mode;remoteGroups=new Set((result.groups||editor.graph.groups).map(g=>g.id));loaded=true;dirty=false;canvas.render();canvas.runtime(mode,result.groups||editor.graph.groups);drawPalette();canvas.fit();canvas.live(result.live||{});editor.message(result.recovery?.warning|| (editor.graph.nodes.length?`${editor.graph.nodes.length} nodes loaded. Monitor live values; right-click to edit or save.`:'No automations were included. Recompile your saved project with the updated Windows app, or add nodes here.'),!!result.recovery?.warning);buttons();}catch(error){editor.message(error.message,true);}finally{loading=false;}}
 async function save(){const validation=problems(editor.graph,editor.specs);if(validation.errors.size)throw Error([...validation.errors.values()].flat().join(' '));busy=true;buttons();try{const result=await request({graph:editor.graph,mode});mode=result.mode;syncGroups(result.groups);if(result.warning){dirty=true;editor.message(result.warning,true);return result;}dirty=false;editor.message(options.local?'Logics saved in project; compile to run on ESP.':'Logics saved and applied on the device and will be restored after reboot.');return result;}finally{busy=false;buttons();}}
 function add(spec,pos,origin,decorate=null){editor.begin();const node=createNode(spec,pos);if(node.type==='audio.piano'){node.parameters.instrument=['piano','bell','guitar','organ'][Math.floor(Math.random()*4)];node.parameters.notes=[[0,4,7,12],[7,4,2,0],[0,2,4,7,5,4],[0,7,9,7]][Math.floor(Math.random()*4)].map((n,i)=>({note:60+n,start:i*.35,duration:.3,velocity:.75}));}editor.graph.nodes.push(node);editor.selected=new Set([node.id]);if(origin){const p=node.ports.find(p=>p.direction!==origin.port.direction&&(origin.port.direction==='output'?compatible(origin.port.type,p.type):compatible(p.type,origin.port.type)));if(p){if(origin.port.direction==='output')connect(editor.graph,origin.node,origin.port.id,node.id,p.id);else connect(editor.graph,node.id,p.id,origin.node,origin.port.id);}}decorate?.(node);editor.changed();return node;}
 function drawPalette(){palette.replaceChildren();const categories=new Map();for(const s of editor.specs){if(!`${s.title} ${s.category} ${s.subcategory||''}`.toLowerCase().includes(search.value.toLowerCase()))continue;const category=s.category==='Active peripherals'?'Active peripherals':s.subcategory?`${s.category} / ${s.subcategory}`:s.category;if(!categories.has(category)){const details=document.createElement('details');details.open=!!search.value;details.ontoggle=()=>{if(details.open)for(const other of palette.querySelectorAll('details'))if(other!==details)other.open=false;};const summary=document.createElement('summary');summary.textContent=category.split(' / ').map(part=>part.split(' · ').map(tr).join(' · ')).join(' / ');summary.title=summary.textContent;details.append(summary);palette.append(details);const choices=document.createElement("div");choices.className="logic-palette-choices";details.append(choices);categories.set(category,details);}const b=document.createElement('button');b.type='button';b.textContent=s.title.split(' · ').map(tr).join(' · ');b.title=editor.help(createNode(s,{x:0,y:0}));b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('application/x-elma-logic',specKey(s));b.onclick=()=>{categories.get(category).open=false;const r=viewport.getBoundingClientRect();add(s,canvas.scene({clientX:r.left+r.width/2,clientY:r.top+r.height/2}));};categories.get(category).querySelector(".logic-palette-choices").append(b);}}
 function deleteSelection(){editor.begin();removeNodes(editor.graph,editor.selected);editor.graph.groups=(editor.graph.groups||[]).map(g=>({...g,nodes:g.nodes.filter(n=>editor.graph.nodes.some(node=>node.id===n))})).filter(g=>g.nodes.length||g.rect);editor.selected.clear();editor.changed();}
 function copySelection(){editor.begin();editor.selected=duplicate(editor.graph,editor.selected);editor.changed();}
 search.oninput=drawPalette;if(saveButton)saveButton.onclick=()=>save().catch(error=>editor.message(error.message,true));viewport.ondragover=e=>{e.preventDefault();};viewport.ondrop=e=>{e.preventDefault();const s=editor.specs.find(s=>specKey(s)===e.dataTransfer.getData('application/x-elma-logic'));if(s)add(s,canvas.scene(e));};
 function undoEdit(){if(!undo.length)return;redo.push(clone(editor.graph));editor.graph=undo.pop();dirty=true;options.onChange?.(clone(editor.graph));canvas.render();buttons();editor.select();}
 function redoEdit(){if(!redo.length)return;undo.push(clone(editor.graph));editor.graph=redo.pop();dirty=true;options.onChange?.(clone(editor.graph));canvas.render();buttons();editor.select();}
 viewport.tabIndex=0;viewport.onkeydown=e=>{if(e.target.closest('input,select,.logic-piano'))return;if(['Delete','Backspace'].includes(e.key)){e.preventDefault();deleteSelection();}else if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();save().catch(error=>editor.message(error.message,true));}else if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redoEdit();}else if(e.ctrlKey&&e.key.toLowerCase()==='c'){clipboard=clone({...editor.graph,nodes:editor.graph.nodes.filter(n=>editor.selected.has(n.id)),connections:editor.graph.connections.filter(e=>editor.selected.has(e.source.node)&&editor.selected.has(e.target.node))});e.preventDefault();}else if(e.ctrlKey&&e.key.toLowerCase()==='v'&&clipboard){editor.begin();const part=clone(clipboard);part.groups=(part.groups||[]).filter(g=>g.nodes.every(n=>part.nodes.some(node=>node.id===n)));const previousGroups=new Set(part.groups.map(g=>g.id)),ids=duplicate(part,new Set(part.nodes.map(n=>n.id)));editor.graph.groups.push(...part.groups.filter(g=>!previousGroups.has(g.id)));editor.graph.nodes.push(...part.nodes.filter(n=>ids.has(n.id)));editor.graph.connections.push(...part.connections.filter(e=>ids.has(e.source.node)));editor.selected=ids;editor.changed();e.preventDefault();}else if(e.ctrlKey&&e.key.toLowerCase()==='z'){(e.shiftKey?redoEdit:undoEdit)();e.preventDefault();}};
 document.addEventListener('pointerdown',e=>{if(menu&&!menu.contains(e.target))menu.remove();if(!palette.contains(e.target)&&e.target!==search)for(const details of palette.querySelectorAll('details[open]'))details.open=false;},true);
 let polling=false;setInterval(async()=>{if(!panel.classList.contains('active')||document.hidden)return;if(!loaded){await load();return;}if(polling)return;polling=true;try{const result=await request(null,true);mode=result.mode;syncGroups(result.groups);canvas.live(result.live||{});if(result.live?.error)editor.message(result.live.error,true);buttons();}catch(error){editor.message(error.message,true);}finally{polling=false;}},1000);
 buttons();return {editor,canvas,load,save,add,replaceProject(graph){editor.graph=clone(graph);editor.graph.groups||=[];editor.graph.view||={grid:true,snap:false};editor.selected.clear();undo=[];redo=[];dirty=false;canvas.render();editor.select();canvas.fit();},refreshDevices(devices){editor.graph.devices=clone(devices);editor.specs=[...Object.values(LOGIC_CATALOG),...devices];upgradeNodes(editor.graph,editor.specs);drawPalette();canvas.render();editor.select();}};
}
