import {LOGIC_CATALOG} from './logic-catalog.js';
import {LOGIC_HELP,PERIPHERAL_HELP} from './logic-help.js';
import {clone,createNode,connect,removeNodes,duplicate,compatible,specKey,problems,upgradeNodes} from './logic-graph-model.js';
import {groupSelection} from './logic-groups.js';
import {createLogicCanvas} from './logic-canvas.js';
export function createLogicsTab(){
 const panel=document.getElementById('tab-logics');if(!panel)return null;
 let loaded=false,loading=false,busy=false,dirty=false,mode='playing',before=null,undo=[],redo=[],clipboard=null,menu=null;let remoteGroups=new Set();
 const status=panel.querySelector('[data-logic-status]'),palette=panel.querySelector('[data-logic-palette]'),properties=panel.querySelector('[data-logic-properties]'),search=panel.querySelector('[data-logic-search]'),viewport=panel.querySelector('[data-logic-canvas]');
 const editor={graph:{schemaVersion:1,nodes:[],connections:[],groups:[],devices:[],view:{grid:true,snap:false}},specs:Object.values(LOGIC_CATALOG),selected:new Set(),
 message(text,error=false){status.textContent=text;status.classList.toggle('error',error);},
 begin(){before=clone(editor.graph);},
 changed(render=true){if(before&&JSON.stringify(before)!==JSON.stringify(editor.graph)){undo.push(before);if(undo.length>100)undo.shift();redo=[];dirty=true;}before=null;if(render)canvas.render();editor.select();buttons();},
 select(){canvas.select();properties.replaceChildren();const node=editor.graph.nodes.find(n=>editor.selected.has(n.id));if(!node)return;const title=document.createElement('input');title.id='logic-selected-name';title.value=node.name;title.setAttribute('aria-label','Node name');title.onchange=()=>{editor.begin();node.name=title.value;editor.changed();};properties.append(title);const help=document.createElement('p');help.textContent=editor.help(node);properties.append(help);for(const [key,value] of Object.entries(node.parameters)){if(typeof value==='object')continue;const row=document.createElement('label');row.textContent=key+' ';row.append(canvas.field(node,key,value,"properties"));properties.append(row);}const found=problems(editor.graph,editor.specs);if(found.errors.has(node.id)){const p=document.createElement('p');p.className='error';p.textContent=found.errors.get(node.id).join(' ');properties.append(p);}},
 help(node){const definition=editor.specs.find(s=>specKey(s)===specKey(node)),help=LOGIC_HELP[node.type]||PERIPHERAL_HELP[node.type.split('.').at(-1)];return (definition?.description||help?.[0]||definition?.title||node.name)+'\nAccepts: '+node.ports.filter(p=>p.direction==='input').map(p=>`${p.label} (${p.type})`).join(', ')+'\nOutputs: '+node.ports.filter(p=>p.direction==='output').map(p=>`${p.label} (${p.type})`).join(', ')+(help?.[1]?'\nExample: '+help[1]:'');},
 link(from,to){editor.begin();if(from.port.direction==='output')connect(editor.graph,from.node,from.port.id,to.node,to.port);else connect(editor.graph,to.node,to.port,from.node,from.port.id);editor.changed();},
 moveLink(from,to){editor.begin();const original=before;try{editor.graph.connections=editor.graph.connections.filter(e=>e.id!==from.edge.id);if(to){if(from.port.direction==='output')connect(editor.graph,from.node,from.port.id,to.node,to.port);else connect(editor.graph,to.node,to.port,from.node,from.port.id);}editor.changed();}catch(error){editor.graph=original;before=null;canvas.render();editor.message(error.message+'; original wire retained',true);}},
 controlGroup:async(group,state)=>{try {if(state==='playing'&&dirty)await save();if(!remoteGroups.has(group.id)){editor.begin();group.mode=state;editor.changed(false);await save();}else {const result=await request({group:{id:group.id,mode:state}});syncGroups(result.groups);if(result.warning){editor.message(result.warning,true);return;}}editor.message(`${group.name}: ${state}.${dirty?' Canvas edits still need Save & apply.':''}`);}catch(error){editor.message(error.message,true);}},
 menu(event,node=null,edge=null,origin=null,position=null,group=null){menu?.remove();menu=document.createElement('div');menu.className='logic-context-menu';menu.style.left=Math.min(event.clientX,window.innerWidth-330)+'px';menu.style.top=Math.min(event.clientY,window.innerHeight-400)+'px';document.body.append(menu);const action=(label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{menu.remove();try{Promise.resolve(fn()).catch(error=>editor.message(error.message,true));}catch(error){editor.message(error.message,true);}};menu.append(b);};
 action('Save & apply',save);action('Fit all',()=>canvas.fit());action('Undo',undoEdit);action('Redo',redoEdit);for(const state of ['playing','paused','stopped'])action('All automations: '+state,async()=>{if(state==='playing'&&dirty)await save();const result=await request({mode:state});mode=result.mode;editor.message(result.warning||'All automations: '+mode,!!result.warning);});
 if(group){for(const state of ['playing','paused','stopped'])action('Automation: '+state,()=>editor.controlGroup(group,state));action('Ungroup',()=>{editor.begin();editor.graph.groups=editor.graph.groups.filter(g=>g.id!==group.id);editor.changed();});action('Rename',()=>{const name=prompt('Automation name',group.name);if(name!==null){editor.begin();group.name=name;editor.changed();}});return;}
 if(node){if(!editor.selected.has(node.id))editor.selected=new Set([node.id]);editor.select();for(const wire of editor.graph.connections.filter(e=>e.source.node===node.id||e.target.node===node.id)){const a=editor.graph.nodes.find(n=>n.id===wire.source.node),b=editor.graph.nodes.find(n=>n.id===wire.target.node);action(`Disconnect: ${a.name}.${wire.source.port} → ${b.name}.${wire.target.port}`,()=>{editor.begin();editor.graph.connections=editor.graph.connections.filter(e=>e.id!==wire.id);editor.changed();});}action('Properties',()=>{editor.select();panel.querySelector('.logic-inspector').open=true;});action('Duplicate',copySelection);action('Break all links',()=>{editor.begin();editor.graph.connections=editor.graph.connections.filter(e=>!editor.selected.has(e.source.node)&&!editor.selected.has(e.target.node));editor.changed();});action('Delete',deleteSelection);}
 else if(edge)action('Delete connection',()=>{editor.begin();editor.graph.connections=editor.graph.connections.filter(e=>e.id!==edge.id);editor.changed();});
 if(editor.selected.size&&!origin&&!edge){action('Group',()=>{editor.begin();groupSelection(editor.graph,editor.selected);editor.changed();});action('Drag selection',()=>editor.message('Grab a selected node header, or the group rectangle, to move it.'));}
 if(!edge){const input=document.createElement('input');input.id='logic-add-node-search';input.placeholder='Add node: search…';menu.append(input);const list=document.createElement('div');list.className='logic-menu-results';menu.append(list);const draw=()=>{list.replaceChildren();const specs=editor.specs.filter(s=>(!origin||s.ports.some(p=>p.direction!==origin.port.direction&&(origin.port.direction==='output'?compatible(origin.port.type,p.type):compatible(p.type,origin.port.type))))&&`${s.title} ${s.category} ${s.subcategory||''}`.toLowerCase().includes(input.value.toLowerCase()));for(const s of specs){const b=document.createElement('button');b.type='button';b.textContent=`${s.category} / ${s.title}`;b.onclick=()=>{menu.remove();add(s,position||canvas.scene(event),origin);};list.append(b);}};input.oninput=draw;draw();input.focus();}
 }
 };
 const canvas=createLogicCanvas(editor,viewport);
 async function request(payload,live=false){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);let response;try{response=await fetch('/api/logics'+(live?'?live=1':''),{cache:'no-store',signal:controller.signal,...(payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{})});}finally{clearTimeout(timeout);}const result=await response.json();if(!response.ok||result.error)throw Error(result.error||`Logics request failed (${response.status})`);return result;}
 function buttons(){panel.querySelector('[data-logic-dirty]').textContent=busy?'Saving…':dirty?'Unsaved changes — device runs last applied graph':loaded?'Saved on device':'';}
 function syncGroups(groups){if(!groups)return;remoteGroups=new Set(groups.map(g=>g.id));for(const group of editor.graph.groups||[]){const remote=groups.find(g=>g.id===group.id);if(remote)group.mode=remote.mode;}for(const group of editor.graph.groups||[]){const box=canvas.stage.querySelectorAll('.logic-group');for(const element of box){const head=element.querySelector('header');if(element.dataset.group!==group.id)continue;const bs=element.querySelectorAll('button');bs[0].classList.toggle('active',group.mode==='playing');bs[1].textContent=group.mode==='paused'?'Resume':'Pause';bs[1].classList.toggle('active',group.mode==='paused');bs[1].onclick=()=>editor.controlGroup(group,group.mode==='paused'?'playing':'paused');bs[2].classList.toggle('active',group.mode==='stopped');}}}
 async function load(){if(loading||loaded)return;loading=true;editor.message('Loading device Logics…');try{const result=await request();editor.graph=clone(result.graph);editor.graph.groups||=[];editor.graph.view||={grid:true,snap:false};editor.graph.devices||=[];editor.specs=[...Object.values(LOGIC_CATALOG).filter(s=>result.audioEnabled!==false||!s.type.startsWith('audio.')||s.type==='audio.piano'),...editor.graph.devices];for(const n of editor.graph.nodes){const s=editor.specs.find(s=>specKey(s)===specKey(n));n.ports||=clone(s?.ports||[]);n.parameters={...clone(s?.parameters||{}),...(n.parameters||{})};n.name||=s?.title||n.type;n.position||={x:0,y:0};}upgradeNodes(editor.graph,editor.specs);mode=result.mode;remoteGroups=new Set((result.groups||editor.graph.groups).map(g=>g.id));loaded=true;dirty=false;canvas.render();drawPalette();canvas.fit();canvas.live(result.live||{});editor.message(editor.graph.nodes.length?`${editor.graph.nodes.length} nodes loaded. Monitor live values; right-click to edit or save.`:'No automations were included. Recompile your saved project with the updated Windows app, or add nodes here.');buttons();}catch(error){editor.message(error.message,true);}finally{loading=false;}}
 async function save(){const validation=problems(editor.graph,editor.specs);if(validation.errors.size)throw Error([...validation.errors.values()].flat().join(' '));busy=true;buttons();try{const result=await request({graph:editor.graph,mode});mode=result.mode;dirty=false;syncGroups(result.groups);editor.message('Logics saved and applied on the device.');}finally{busy=false;buttons();}}
 function add(spec,pos,origin){editor.begin();const node=createNode(spec,pos);if(node.type==='audio.piano'){node.parameters.instrument=['piano','bell','guitar','organ'][Math.floor(Math.random()*4)];node.parameters.notes=[0,4,7,12].map((n,i)=>({note:60+n,start:i*.35,duration:.3,velocity:.75}));}editor.graph.nodes.push(node);editor.selected=new Set([node.id]);if(origin){const p=node.ports.find(p=>p.direction!==origin.port.direction&&(origin.port.direction==='output'?compatible(origin.port.type,p.type):compatible(p.type,origin.port.type)));if(p){if(origin.port.direction==='output')connect(editor.graph,origin.node,origin.port.id,node.id,p.id);else connect(editor.graph,node.id,p.id,origin.node,origin.port.id);}}editor.changed();}
 function drawPalette(){palette.replaceChildren();const categories=new Map();for(const s of editor.specs){if(!`${s.title} ${s.category} ${s.subcategory||''}`.toLowerCase().includes(search.value.toLowerCase()))continue;const category=s.category==='Active peripherals'?'Active peripherals':s.subcategory?`${s.category} / ${s.subcategory}`:s.category;if(!categories.has(category)){const details=document.createElement('details');details.open=!!search.value;details.ontoggle=()=>{if(details.open)for(const other of palette.querySelectorAll('details'))if(other!==details)other.open=false;};const summary=document.createElement('summary');summary.textContent=category;details.append(summary);palette.append(details);const choices=document.createElement("div");choices.className="logic-palette-choices";details.append(choices);categories.set(category,details);}const b=document.createElement('button');b.type='button';b.textContent=s.title;b.title=editor.help(createNode(s,{x:0,y:0}));b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('application/x-elma-logic',specKey(s));b.onclick=()=>{categories.get(category).open=false;const r=viewport.getBoundingClientRect();add(s,canvas.scene({clientX:r.left+r.width/2,clientY:r.top+r.height/2}));};categories.get(category).querySelector(".logic-palette-choices").append(b);}}
 function deleteSelection(){editor.begin();removeNodes(editor.graph,editor.selected);editor.graph.groups=(editor.graph.groups||[]).map(g=>({...g,nodes:g.nodes.filter(n=>editor.graph.nodes.some(node=>node.id===n))})).filter(g=>g.nodes.length||g.rect);editor.selected.clear();editor.changed();}
 function copySelection(){editor.begin();editor.selected=duplicate(editor.graph,editor.selected);editor.changed();}
 search.oninput=drawPalette;viewport.ondragover=e=>{e.preventDefault();};viewport.ondrop=e=>{e.preventDefault();const s=editor.specs.find(s=>specKey(s)===e.dataTransfer.getData('application/x-elma-logic'));if(s)add(s,canvas.scene(e));};
 function undoEdit(){if(!undo.length)return;redo.push(clone(editor.graph));editor.graph=undo.pop();dirty=true;canvas.render();buttons();editor.select();}
 function redoEdit(){if(!redo.length)return;undo.push(clone(editor.graph));editor.graph=redo.pop();dirty=true;canvas.render();buttons();editor.select();}
 viewport.tabIndex=0;viewport.onkeydown=e=>{if(e.target.closest('input,select,.logic-piano'))return;if(['Delete','Backspace'].includes(e.key)){e.preventDefault();deleteSelection();}else if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();save().catch(error=>editor.message(error.message,true));}else if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redoEdit();}else if(e.ctrlKey&&e.key.toLowerCase()==='c'){clipboard=clone({...editor.graph,nodes:editor.graph.nodes.filter(n=>editor.selected.has(n.id)),connections:editor.graph.connections.filter(e=>editor.selected.has(e.source.node)&&editor.selected.has(e.target.node))});e.preventDefault();}else if(e.ctrlKey&&e.key.toLowerCase()==='v'&&clipboard){editor.begin();const part=clone(clipboard);part.groups=(part.groups||[]).filter(g=>g.nodes.every(n=>part.nodes.some(node=>node.id===n)));const previousGroups=new Set(part.groups.map(g=>g.id)),ids=duplicate(part,new Set(part.nodes.map(n=>n.id)));editor.graph.groups.push(...part.groups.filter(g=>!previousGroups.has(g.id)));editor.graph.nodes.push(...part.nodes.filter(n=>ids.has(n.id)));editor.graph.connections.push(...part.connections.filter(e=>ids.has(e.source.node)));editor.selected=ids;editor.changed();e.preventDefault();}else if(e.ctrlKey&&e.key.toLowerCase()==='z'){(e.shiftKey?redoEdit:undoEdit)();e.preventDefault();}};
 document.addEventListener('pointerdown',e=>{if(menu&&!menu.contains(e.target))menu.remove();});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 let polling=false;setInterval(async()=>{if(!panel.classList.contains('active')||document.hidden)return;if(!loaded){await load();return;}if(polling)return;polling=true;try{const result=await request(null,true);mode=result.mode;syncGroups(result.groups);canvas.live(result.live||{});if(result.live?.error)editor.message(result.live.error,true);buttons();}catch(error){editor.message(error.message,true);}finally{polling=false;}},1000);
 buttons();return {editor,canvas,load,save};
}
