const BASE='https://elma-iot.github.io/elma-iot-docs';
const SUPPORTED=new Set(['en','es','zh','hi','ar','pt','bn','ru','ja','de','fr','ko','tr','it','id','pl','uk','vi','th','fa']);
export function helpLocale(){const raw=String(window.ElmaI18n?.language||window.ElmaFirmwareI18n?.language||document.documentElement.lang||navigator.language||'en').toLowerCase().replace('_','-').split('-')[0];return SUPPORTED.has(raw)?raw:'en';}
export function helpIdForNode(node){if(node?.helpId)return node.helpId;const type=String(node?.type||'');const map={'flow.gate':'logics.gate','flow.sequence':'logics.sequence','flow.branch':'logics.branch','timing.delay':'logics.delay','timing.timer':'logics.timer','timing.repeat':'logics.repeat','timing.debounce':'logics.debounce','timing.cooldown':'logics.cooldown','condition.compare':'logics.compare','condition.if':'logics.if','mainboard.mqtt.publish':'mqtt.publish'};if(node?.peripheral?.profile){let value=String(node.peripheral.profile).split(':').at(-1).replaceAll('_','-');if(['buzzer','custom','es8388-audio-codec','wm8960-audio-codec'].includes(value))value=String(node.peripheral.group||'hardware').replaceAll('_','-')+'-'+value;return 'peripheral.'+value;}return map[type]||('logics.'+type.replaceAll('.','-').replaceAll('_','-'));}
export function helpUrl(helpId='home',locale=helpLocale()){const topic=String(helpId||'home').replace(/^\.+|\.+$/g,'');return BASE+'/'+locale+'/'+(topic==='home'?'':topic.split('.').map(encodeURIComponent).join('/')+'/');}
export function openOnlineHelp(helpId='home'){if(navigator.onLine===false){alert('Online documentation requires an Internet connection.');return false;}const url=helpUrl(helpId),opened=window.open(url,'_blank','noopener,noreferrer');if(!opened&&!window.ElmaAndroidConfig){alert('Unable to open online documentation. Check the Internet connection and allow pop-ups for this device.');return false;}return true;}
const TAB_HELP={gpio:'setup.gpio',logics:'logics.overview',motor:'setup.peripherals',playback:'audio.overview',effects:'audio.overview',wifi:'wifi',mqtt:'mqtt.overview',battery:'peripheral.voltage-divider',device:'web-interface',oled:'setup.peripherals',hardware:'web-interface','storage-internal':'setup.peripherals','storage-external':'setup.peripherals',migration:'setup.overview',firmware:'flash.ota',logs:'serial-monitor',info:'about'};
export function installOnlineHelpLinks(){
 if(document.getElementById('elma-online-help-style'))return;
 const style=document.createElement('style');style.id='elma-online-help-style';
 style.textContent='.online-help-heading{display:flex;align-items:center;gap:.48rem;width:max-content;max-width:100%;margin:0 0 .65rem}.online-help-heading>h1,.online-help-heading>h2,.online-help-heading>h3{margin:0}.online-help-button{box-sizing:border-box;display:inline-flex;flex:0 0 1.55rem;width:1.55rem!important;height:1.55rem;min-width:1.55rem;min-height:1.55rem;margin:0!important;padding:0!important;align-items:center;justify-content:center;border:2px solid #ef9a00!important;border-radius:50%!important;background:transparent!important;color:#ffc04a!important;font:700 .95rem/1 Georgia,serif!important;box-shadow:none!important}.online-help-button:hover,.online-help-button:focus-visible{background:#ef9a00!important;color:#101821!important;outline:none;box-shadow:0 0 0 3px #ef9a0040!important}.logic-context-menu .online-help-menu{border-color:#ef8b00}';document.head.append(style);
 for(const [tab,id] of Object.entries(TAB_HELP)){
  const panel=document.getElementById('tab-'+tab);if(!panel)continue;
  let heading=panel.querySelector(':scope > h1,:scope > h2,:scope > h3,:scope > .device-log-heading > h2');
  if(!heading){heading=document.createElement('h2');heading.textContent=panel.getAttribute('aria-label')||document.querySelector(`[aria-controls="tab-${tab}"]`)?.getAttribute('aria-label')||tab;panel.prepend(heading);}
  let row=heading.parentElement?.classList.contains('online-help-heading')?heading.parentElement:null;
  if(!row){row=document.createElement('div');row.className='online-help-heading';heading.before(row);row.append(heading);}
  const label=window.ElmaI18n?.t?.('Help')||'Help';const button=document.createElement('button');button.type='button';button.className='online-help-button';button.textContent='i';button.title=label;button.setAttribute('aria-label',label);button.dataset.helpId=id;button.onclick=()=>openOnlineHelp(id);row.append(button);
 }
}
