import assert from 'node:assert/strict';
import {routeGeometry,validRouting,constrainHandles,enableHandles,groupRoutes,moveGroupRoutes} from '../web/modules/logic-routing.js';
import {duplicate} from '../web/modules/logic-graph-model.js';
const point={x:100,y:30,controlIn:{x:-40,y:0},controlOut:{x:40,y:0}};
const edge={id:'e',source:{node:'a',port:'out'},target:{node:'b',port:'in'},routingPoints:[point]};
assert(validRouting(edge));const a={x:0,y:0},b={x:200,y:0},first=routeGeometry(a,b,[point]);point.controlIn.y=50;const second=routeGeometry(a,b,[point]);assert.notEqual(first.segments[0],second.segments[0]);assert.equal(first.segments[1],second.segments[1]);
assert(!validRouting({...edge,routingPoints:[{x:0,y:0,controlIn:{x:0,y:0}}]}));assert(!validRouting({...edge,routingPoints:[{x:Infinity,y:0}]}));
const graph={nodes:[{id:'a',type:'event.start',position:a},{id:'b',type:'timing.delay',position:b}],connections:[edge],groups:[],view:{labels:[]}};duplicate(graph,new Set(['a','b']),{x:50,y:20});assert.deepEqual(graph.connections[1].routingPoints[0],{...point,x:150,y:50});
console.log('PASS: geometry, independent handles, validation and duplicate offsets');
const limited=[{x:100,y:0,controlIn:{x:0,y:999},controlOut:{x:1,y:0}}];
constrainHandles(limited,{x:0,y:0},{x:300,y:0});
assert.deepEqual(limited[0].controlIn,{x:0,y:50});assert.deepEqual(limited[0].controlOut,{x:20,y:0});
limited[0].controlIn={x:0,y:0};constrainHandles(limited,{x:0,y:0},{x:300,y:0});assert.deepEqual(limited[0].controlIn,{x:-10,y:0});
constrainHandles(limited,{x:100,y:0},{x:100,y:0});assert.equal(Math.hypot(...Object.values(limited[0].controlIn)),0);
console.log('PASS: 10–50% straight-chord bounds, independent directions and coincident points');
const fresh={routingPoints:[{x:100,y:0}]};enableHandles(fresh,0,{x:0,y:0},{x:300,y:0},{dots:[{x:100,y:0}]},{x:0,y:0});
assert.equal(fresh.routingPoints[0].controlIn.x,-(100/3+50)/2);assert.equal(fresh.routingPoints[0].controlOut.x,(60+100)/2);
console.log('PASS: new controls average original reach and 50% limit');
const external={connections:[{source:{node:'outside1'},target:{node:'outside2'},routingPoints:[{x:50,y:50,controlIn:{x:-10,y:0},controlOut:{x:10,y:0}},{x:150,y:50}]}]};
const owned=groupRoutes(external,{nodes:[]},{x:0,y:0,width:100,height:100});moveGroupRoutes(owned,20,30);moveGroupRoutes(owned,30,40);
assert.deepEqual(external.connections[0].routingPoints,[{x:80,y:90,controlIn:{x:-10,y:0},controlOut:{x:10,y:0}},{x:150,y:50}]);
console.log('PASS: group containment moves external-wire dots exactly once, leaving outside dots unchanged');
