// Exercise production persistence with memory-backed FS/NVS, including failed writes.
#include <ArduinoJson.h>
#include <string>
#include <map>
#include <cstring>
#include <cassert>
#include <iostream>
using String=std::string;
enum class StorageTarget{Flash,Sd};
namespace fs {struct FS{std::map<std::string,std::string> files;bool failRename=false;bool rename(const char* a,const char* b){if(failRename||files.count(b))return false;files[b]=files[a];files.erase(a);return true;}void remove(const char* path){files.erase(path);}};}
fs::FS flash,sd;bool flashMounted=false,sdMounted=false,nvsWrite=true;
struct File{std::string* data=nullptr;size_t at=0;explicit operator bool()const{return data;}size_t write(uint8_t byte){data->push_back(char(byte));return 1;}size_t write(const uint8_t* bytes,size_t count){data->append(reinterpret_cast<const char*>(bytes),count);return count;}int read(){return data&&at<data->size()?uint8_t((*data)[at++]):-1;}size_t readBytes(char* out,size_t count){size_t n=0;while(n<count){int c=read();if(c<0)break;out[n++]=char(c);}return n;}void flush(){}void close(){}};
bool storageMounted(StorageTarget target){return target==StorageTarget::Flash?flashMounted:sdMounted;}
fs::FS* getStorageFs(StorageTarget target){return storageMounted(target)?target==StorageTarget::Flash?&flash:&sd:nullptr;}
File storageOpen(StorageTarget target,const char* path,const char* mode="r"){auto fs=getStorageFs(target);if(!fs||(*mode=='w'&&fs->failRename))return {};if(*mode=='w')fs->files[path].clear();auto item=fs->files.find(path);return item==fs->files.end()?File{}:File{&item->second};}
void beginStorageRead(StorageTarget){}void endStorageRead(StorageTarget){}void beginStorageWrite(StorageTarget){}void endStorageWrite(StorageTarget){}
struct Preferences{static std::map<std::string,std::string> blobs;static uint32_t revision;static size_t capacity;std::string space;uint32_t getUInt(const char*,uint32_t fallback){return revision?revision:fallback;}size_t putUInt(const char*,uint32_t value){if(!nvsWrite)return 0;revision=value;return 4;}uint8_t getUChar(const char* key,uint8_t fallback){auto it=blobs.find(space+":"+key);return it==blobs.end()||it->second.empty()?fallback:uint8_t(it->second[0]);}size_t putUChar(const char* key,uint8_t value){if(!nvsWrite)return 0;blobs[space+":"+key]=std::string(1,char(value));return 1;}bool begin(const char* name,bool){space=name;return true;}void end(){}size_t getBytesLength(const char* key){auto it=blobs.find(space+":"+key);return it==blobs.end()?0:it->second.size();}size_t getBytes(const char* key,void* out,size_t n){auto it=blobs.find(space+":"+key);if(it==blobs.end()||it->second.size()<n)return 0;std::memcpy(out,it->second.data(),n);return n;}size_t putBytes(const char* key,const void* data,size_t n){if(!nvsWrite||n>capacity)return 0;blobs[space+":"+key].assign(static_cast<const char*>(data),n);return n;}bool remove(const char* key){blobs.erase(space+":"+key);return true;}bool clear(){for(auto it=blobs.begin();it!=blobs.end();)if(it->first.rfind(space+":",0)==0)it=blobs.erase(it);else ++it;revision=0;return true;}};std::map<std::string,std::string> Preferences::blobs;uint32_t Preferences::revision=0;size_t Preferences::capacity=40000;
#define ELMA_LOGIC_STORAGE_HOST
#include "../src/logic_storage.cpp"
int main(){
 {JsonDocument bulky,loaded;String error;bulky["source"]=99;bulky["mode"]="playing";bulky["graph"]["devices"]=std::string(10000,'x');auto n=bulky["graph"]["nodes"].to<JsonArray>().add<JsonObject>();n["id"]="number";n["type"]="value.number";n["parameters"]["value"]=60;n["parameters"]["notes"]=std::string(6500,'x');n["position"]["x"]=123;n["ports"]=std::string(10000,'x');n["binding"]=std::string(10000,'x');Preferences::capacity=1100;assert(measureJson(bulky)>20000);assert(saveLogicRecord(bulky.as<JsonVariantConst>(),error));assert(Preferences::blobs["elma-logics:compact"].empty());assert(Preferences::blobs["elma-logics:b00"].size()<=1000);assert(Preferences::blobs["elma-logics:b01"].size()>0);assert(loadLogicRecord(loaded));assert(loaded["graph"]["nodes"][0]["parameters"]["value"]==60);assert(loaded["graph"]["nodes"][0]["parameters"]["notes"].as<std::string>().size()==6500);assert(loaded["graph"]["nodes"][0]["position"]["x"]==123);assert(loaded["graph"]["devices"].isNull());assert(loaded["graph"]["nodes"][0]["ports"].isNull());Preferences::blobs.clear();Preferences::revision=0;Preferences::capacity=40000;latestRevision=0;}
 JsonDocument record,restored;String error;record["source"]=99;record["mode"]="playing";record["graph"]["threshold"]=50;
 sdMounted=true;sd.files["/.elma-logics.json"]="{\"revision\":0,\"source\":99,\"graph\":{\"threshold\":40}}";assert(saveLogicRecord(record.as<JsonVariantConst>(),error));assert(loadLogicRecord(restored));assert(restored["graph"]["threshold"]==50);assert(sd.files.count("/.elma-logics.1.json"));assert(Preferences::blobs.empty());
 record["graph"]["threshold"]=60;record["mode"]="stopped";assert(saveLogicRecord(record.as<JsonVariantConst>(),error));assert(loadLogicRecord(restored));assert(restored["graph"]["threshold"]==60&&restored["mode"]=="stopped");
 sdMounted=false;record["graph"]["large"]=std::string(6500,'x');record["mode"]="paused";assert(saveLogicRecord(record.as<JsonVariantConst>(),error));sdMounted=true;assert(loadLogicRecord(restored));assert(restored["mode"]=="paused");assert(restored["graph"]["large"].as<std::string>().size()==6500);
 sd.failRename=true;nvsWrite=false;record["graph"]["threshold"]=70;assert(!saveLogicRecord(record.as<JsonVariantConst>(),error));assert(loadLogicRecord(restored));assert(restored["graph"]["threshold"]==60);assert(!error.empty());
 std::cout<<"PASS: SD without LittleFS, NVS multi-page blob, latest revision restoration, failed-write previous graph retained\n";
}
