// Portrait forms use the same JSON paths and validators as the web settings.
// page, caption, path, control type, choices, minimum, maximum
struct PanelFormField {const char* page;const char* caption;const char* path;const char* kind;const char* options;double minimum;double maximum;};
static const PanelFormField panelFormFields[]={
 {"gpio","Status LED GPIO","device/statusLedPin","number","",-1,48},
 {"gpio","Status LED type","device/statusLedType","select","regular\nneopixel\nrgb",0,0},
 {"wifi","Network name (SSID)","wifi/ssid","text","",0,0},
 {"wifi","Wi-Fi password","wifi/password","secret","",0,0},
 {"wifi","Access point name","wifi/apSsid","text","",0,0},
 {"wifi","Access point password","wifi/apPassword","secret","",0,0},
 {"wifi","AP fallback","wifi/apFallbackEnabled","switch","",0,0},
 {"wifi","Static IP","wifi/useStaticIp","switch","",0,0},
 {"wifi","IP address","wifi/staticIp","text","",0,0},
 {"wifi","Gateway","wifi/gateway","text","",0,0},
 {"wifi","Subnet","wifi/subnet","text","",0,0},
 {"wifi","DNS 1","wifi/dns1","text","",0,0},
 {"wifi","DNS 2","wifi/dns2","text","",0,0},
 {"wifi","STA transmit power (dBm)","wifi/staTxPowerDbm","number","",2,20},
 {"wifi","AP transmit power (dBm)","wifi/apTxPowerDbm","number","",2,20},
 {"mqtt","Host","mqtt/host","text","",0,0},
 {"mqtt","Port","mqtt/port","number","",1,65535},
 {"mqtt","Username","mqtt/username","text","",0,0},
 {"mqtt","Password","mqtt/password","secret","",0,0},
 {"mqtt","Client ID","mqtt/clientId","text","",0,0},
 {"mqtt","Base topic","mqtt/baseTopic","text","",0,0},
 {"mqtt","Discovery","mqtt/discoveryEnabled","switch","",0,0},
 {"device","Device name","device/deviceName","text","",0,0},
 {"device","Friendly name","device/friendlyName","text","",0,0},
 {"device","Mute audio","device/audioMuted","switch","",0,0},
 {"device","Remember volume (%)","device/savedVolumePercent","slider","",0,100},
 {"device","Low-battery sleep","device/lowBatterySleepEnabled","switch","",0,0},
 {"device","Sleep below (%)","device/lowBatterySleepThresholdPercent","number","",0,100},
 {"device","Wake interval (minutes)","device/lowBatteryWakeIntervalMinutes","number","",1,1440},
 {"device","Power-cycle factory reset","device/powerCycleFactoryResetEnabled","switch","",0,0},
 {"device","Touch-hold factory reset","device/touchHoldFactoryResetEnabled","switch","",0,0},
 {"oled","Backlight (%)","oled/brightness","slider","",0,100},
 {"oled","Rotation","oled/rotation","select","0\n90\n180\n270",0,0},
 {"oled","Dim timeout (seconds)","oled/dimTimeoutSeconds","number","",0,86400},
 {"oled","Touchscreen enabled","oled/touchEnabled","switch","",0,0},
 {"oled","Interface","oled/interfaceMode","select","lvgl\ntext",0,0},
 {"playback","Remember last played","audio/rememberLastPlayed","switch","",0,0},
 {"playback","Resume after boot","audio/lastPlayback/resumeAfterBoot","switch","",0,0},
 {"playback","Equalizer","audio/equalizerPreset","select","custom\nflat\nclear\nrock\nbass\nclassical\nvoice\njazz\npodcast\nnight",0,0},
 {"playback","Low (dB)","audio/equalizerLowDb","number","",-40,6},
 {"playback","Presence (dB)","audio/equalizerPresenceDb","number","",-40,6},
 {"playback","High (dB)","audio/equalizerHighDb","number","",-40,6},
 {"battery","Measured voltage (V)","battery/measuredVoltage","number","",0,100},
 {"battery","Calibration multiplier","battery/calibrationMultiplier","number","",0.01,100},
 {"battery","Divider R1 (ohms)","battery/dividerR1Ohms","number","",0,10000000},
 {"battery","Divider R2 (ohms)","battery/dividerR2Ohms","number","",1,10000000},
 {"battery","Maximum input (V)","battery/dividerMaxVin","number","",0,100},
 {"battery","Sampling interval (ms)","battery/updateIntervalMs","number","",100,60000},
 {"battery","Average samples","battery/movingAverageWindowSize","number","",1,100},
 {"firmware","Repository owner","ota/owner","text","",0,0},
 {"firmware","Repository","ota/repository","text","",0,0},
 {"firmware","Channel","ota/channel","select","release\nbeta",0,0},
 {"firmware","Automatic checks","ota/autoCheck","switch","",0,0},
 {"firmware","Automatic updates","ota/autoUpdate","switch","",0,0},
};
